name = "gemini2api"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["fixup-transform-stream-backpressure", "enable_request_signal", "request_signal_passthrough"]
keep_vars = true

[triggers]
crons = ["* * * * *"]

[[durable_objects.bindings]]
name = "COOKIE_STORE"
class_name = "CookieStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CookieStore"]

[[durable_objects.bindings]]
name = "GENERATION_RUNNER"
class_name = "GenerationRunner"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GenerationRunner"]
